public function getShortestPath(int $uid1, int $uid2, int $deep): array
    {
        $subQuery = \DB::table('facebook_friends', 'a')
            ->addSelect('a.user_id as User0');

        $notIn = [];
        $resultIn = [];

        for ($i = 0; $i <= $deep; $i++) {
            if ($i !== 0) {
                $notIn[] = sprintf('%s.user_id', $this->chars[$i - 1]);
                $resultIn[] = sprintf('result.User%s', $i);

                $subQuery
                    ->addSelect(sprintf('%s.friend_id as User%s', $this->chars[$i - 1], $i))
                    ->leftJoin(
                        sprintf('facebook_friends as %s', $this->chars[$i]),
                        function (JoinClause $join) use (&$i, &$notIn) {
                            // joining user with friend
                            $join->on(
                                sprintf('%s.user_id', $this->chars[$i]),
                                '=',
                                sprintf('%s.friend_id', $this->chars[$i - 1])
                            );
                            // exclude self join
                            $join->whereRaw(
                                sprintf('%s.friend_id not in(%s)', $this->chars[$i], implode(',', $notIn))
                            );
                        });

            }
        }

        $subQuery->where('a.user_id', $uid1);

        $query = \DB::query()
            ->from($subQuery, 'result')
            ->whereRaw(sprintf('%d in(%s)', $uid2, implode(',', $resultIn)));

        // Getting all paths.
        $result = $query->get();

        // Filtering the shortest one.
        return $result
            ->map(fn($record) => array_filter(array_values((array) $record)))
            ->sortBy(fn($record) => count($record))
            ->first();
    }


// This is a final script generated by this method.

/**
            
select *
from (select `a`.`user_id`   as `User0`,
             `a`.`friend_id` as `User1`,
             `b`.`friend_id` as `User2`,
             `c`.`friend_id` as `User3`,
             `d`.`friend_id` as `User4`
      from `facebook_friends` as `a`
               left join `facebook_friends` as `b` on `b`.`user_id` = `a`.`friend_id` and b.friend_id not in (a.user_id)
               left join `facebook_friends` as `c`
                         on `c`.`user_id` = `b`.`friend_id` and c.friend_id not in (a.user_id, b.user_id)
               left join `facebook_friends` as `d`
                         on `d`.`user_id` = `c`.`friend_id` and d.friend_id not in (a.user_id, b.user_id, c.user_id)
               left join `facebook_friends` as `e` on `e`.`user_id` = `d`.`friend_id` and
                                                      e.friend_id not in (a.user_id, b.user_id, c.user_id, d.user_id)
      where `a`.`user_id` = '1') as `result`
where 4 in (result.User1, result.User2, result.User3, result.User4)
            
*/
